### ISSUE TITLE
Prioritäten bei Mitteilungen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/portal#7]
Mitteilungen sollten Prioritäten haben:

- Notfall
- Wichtig
- Normal

Innerhalb der Prioritäten sollten noch zu bestätigenden Mitteilung oben stehen. User müssen die Prioritäten zugewiesen bekommen (oberhalb von Normal).

**Comment by M-Plu** [comment]
Farbige Absetzungen wären gut.

**Comment by frostieDE** [comment]
Wie soll die Reihenfolge innerhalb dieser Priotitäten sein?

**Comment by M-Plu** [comment]
Das sollte der User festlegen können. Ablaufdatum und Erstellungsdatum/letzte Änderungen (jeweils auf und absteigend) wären meine Vorschläge.
