### ISSUE TITLE
Updates für Mitteilungen

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/portal#8]
Mitteilungen sollten ein Update-Funktion erhalten. wird eine Mitteilung geändert, so kann der Benutzer entweder einfachen "Änderungen speichern" wählen (so wie bisher), oder er hakt zusätzlich die Option "Änderungen als Aktualisierung mitteilen" an. Wenn er das macht, hast das die folgende Konsequenzen.

- Er muss ein Feld ausfüllen, dass die Updates beschreibt. Dieses wird unterhalb/oberhalb (?) der original mit entsprechenden Infos (User, Zeit, usw.) angezeigt.
- Die Mitteilung wird bei den Benutzern wieder angezeigt, falls sie ausgeblendet war.
- Die Mitteilung wird den Usern als Update mitgeteilt (E-Mail oder Push)

**Comment by frostieDE** [comment]
Das Feature wurde anders implementiert. Man kann innerhalb der Mitteilung farbliche Blöcke erstellen:

![grafik](https://user-images.githubusercontent.com/3764924/77962030-1db49680-72db-11ea-950b-d04da1a4cf62.png)
